<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>communication_contact_address_book_contacts_icon_191613.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="contact photo.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="communication_contact_address_book_contacts_icon_191613.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="contact photo.png" />
  </ItemGroup>

</Project>
